### ISSUE TITLE
 setup_subscriptions.ps1 fails due to Error = 0x2

### ISSUE THREAD

**Issue by hayhahacker** [ElasticSA/wec_pepped#2]
The system cannot find the file specified.
Failed to open subscription. Error = 0x2.

wecutils does not generate error in try clause that PowerShell understands (cmd utill vs PowerShell cmdlets). this means that $doUpdate variable is never updated to $false as catch clause is never ran

I have fixed this changing to following in setup_subscriptions.ps1 file.
  ```
  foreach ( $chan in $ChannelList.GetEnumerator() ) {

       **<# $doUpdate = $true
        try {
            & wecutil gs "$($prov.key)_$($chan.key)" | Out-Null
        }
        catch {
            $doUpdate = $false
        } #>**
        $doUpdate = $true
        & wecutil gs "$($prov.key)_$($chan.key)" 2>&1>$null

        if ("$LASTEXITCODE" -eq 2){
        $doUpdate = $false
        }
}
```

**Comment by ThorbenJ** [comment]
Hi, that's interesting.

Could you provide the PowerShell and Windows version you're running?
In Powershell:
```
echo $PSVersionTable
echo ([Environment]::OSVersion)
```

Thanks
-T

**Comment by hayhahacker** [comment]
PS C:\Users\Administrator> echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\Administrator> echo ([Environment]::OSVersion)

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17763.0 Microsoft Windows NT 10.0.17763.

**Comment by ThorbenJ** [comment]
Thanks. That close enough to my test env.
I ask because with `$ErrorActionPreference = "Stop"` (at the start of the script) PowerShell should (and does for me) stop with an error if any exec outputs to stderr (one char is enough) or returns anything other than success (0).
I'm not so keen on testing for a specific error code, I will have to check and test some more.
-Thorben

**Comment by Plasticjesus** [comment]
I also see this issue. I am using server 2019. I used the fix @hayhahacker  provided but changed the if statement a bit.

**Comment by ThorbenJ** [comment]
Yes, I have been able to replicate this, and I will push a fix; possibly a variation on that from hayhahacker. However it maybe after my summer vacation.

**Comment by ThorbenJ** [comment]
This should now be fixed.

I thought about:
```
 & wecutil gs "$($prov.key)_$($chan.key)" 2>&1 | Out-Null
 $doUpdate = If ($LASTEXITCODE -ne 0) { $false } Else { $true } 
```

However I really wanted to know why PS was no longer treating output to stderr as an error, as it should.
Turns out doing `2>&1` or `*>&1` will cause stderr to be wrapped by the error handler again. 

So I fixed the original try/catch:
```
         $doUpdate = $true
        try {
            & wecutil gs "$($prov.key)_$($chan.key)" *>&1 |Out-Null
        }
        catch {
            $doUpdate = $false
        } 
```

BTW for testing, here's a quick way to clear/remove all subscriptions in PS:
`wecutil.exe es | %{ wecutil.exe ds $_ }`
